### ISSUE TITLE
ClientSession doesn't close

### ISSUE THREAD

**Issue by milanmeu** [stefano055415/pyfreedompro#1]
>Error doing job: Unclosed connection

The problem is reported by the GitHub CI output of PR https://github.com/home-assistant/core/pull/46332 on line 147: https://github.com/home-assistant/core/pull/46332/checks?check_run_id=2120495106#step:8:147

`aiohttp` has the advantage that it can make multiple requests with one connection. Therefore, a connection must be created manually and only closed after all requests have been made. The library user has to create and close the connection, not the library. The user must therefore be able to provide his own connection through a parameter.

I will make a PR to adjust this. This will be a breaking change, it doesn't seem necessary to make it backward compatible.

**Comment by stefano055415** [comment]
Thanks
